### ISSUE TITLE
Broken img src link is causing tests to fail

### ISSUE THREAD

**Issue by ThisIsTyDell** [learn-co-curriculum/css-issue-bot-9000#1]
The following images do not match those found in the test. One link actually doesn't even open an image anymore. Please update the sources or update the screenshot found in the skins folder to allow tests to pass. 

<img src="http://pictures.wayn.com/photos/180c/034546087_237927497.jpg" alt="Adam">
  <img src="http://38.media.tumblr.com/70ace162d8f0654f3239aa7447a21870/tumblr_muvabkXjsz1qz6h81o1_1280.jpg" alt="Avi">

This file is no longer accessible.

**Comment by AnnJohn** [comment]
hi @ThisIsTyDell we removed the testing from our html and css labs because they were causing larger issues. Sorry about the trouble that you were having.
